/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkCategoryRouteImport } from './routes/work.$category'
import { Route as WorkBlogContentRouteImport } from './routes/work.blog-content'
import { Route as WorkBrandingRouteImport } from './routes/work.branding'
import { Route as WorkEmailMarketingRouteImport } from './routes/work.email-marketing'
import { Route as WorkPrintDigitalRouteImport } from './routes/work.print-digital'
import { Route as WorkSocialMediaRouteImport } from './routes/work.social-media'
import { Route as WorkVideoRouteImport } from './routes/work.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCategoryRoute = WorkCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => WorkRoute,
} as any)
const WorkBlogContentRoute = WorkBlogContentRouteImport.update({
  id: '/blog-content',
  path: '/blog-content',
  getParentRoute: () => WorkRoute,
} as any)
const WorkBrandingRoute = WorkBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => WorkRoute,
} as any)
const WorkEmailMarketingRoute = WorkEmailMarketingRouteImport.update({
  id: '/email-marketing',
  path: '/email-marketing',
  getParentRoute: () => WorkRoute,
} as any)
const WorkPrintDigitalRoute = WorkPrintDigitalRouteImport.update({
  id: '/print-digital',
  path: '/print-digital',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSocialMediaRoute = WorkSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => WorkRoute,
} as any)
const WorkVideoRoute = WorkVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect': typeof ConnectRoute
  '/skills': typeof SkillsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$category': typeof WorkCategoryRoute
  '/work/blog-content': typeof WorkBlogContentRoute
  '/work/branding': typeof WorkBrandingRoute
  '/work/email-marketing': typeof WorkEmailMarketingRoute
  '/work/print-digital': typeof WorkPrintDigitalRoute
  '/work/social-media': typeof WorkSocialMediaRoute
  '/work/video': typeof WorkVideoRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect': typeof ConnectRoute
  '/skills': typeof SkillsRoute
  '/work/$category': typeof WorkCategoryRoute
  '/work/blog-content': typeof WorkBlogContentRoute
  '/work/branding': typeof WorkBrandingRoute
  '/work/email-marketing': typeof WorkEmailMarketingRoute
  '/work/print-digital': typeof WorkPrintDigitalRoute
  '/work/social-media': typeof WorkSocialMediaRoute
  '/work/video': typeof WorkVideoRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect': typeof ConnectRoute
  '/skills': typeof SkillsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$category': typeof WorkCategoryRoute
  '/work/blog-content': typeof WorkBlogContentRoute
  '/work/branding': typeof WorkBrandingRoute
  '/work/email-marketing': typeof WorkEmailMarketingRoute
  '/work/print-digital': typeof WorkPrintDigitalRoute
  '/work/social-media': typeof WorkSocialMediaRoute
  '/work/video': typeof WorkVideoRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/connect'
    | '/skills'
    | '/work'
    | '/work/$category'
    | '/work/blog-content'
    | '/work/branding'
    | '/work/email-marketing'
    | '/work/print-digital'
    | '/work/social-media'
    | '/work/video'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/connect'
    | '/skills'
    | '/work/$category'
    | '/work/blog-content'
    | '/work/branding'
    | '/work/email-marketing'
    | '/work/print-digital'
    | '/work/social-media'
    | '/work/video'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/connect'
    | '/skills'
    | '/work'
    | '/work/$category'
    | '/work/blog-content'
    | '/work/branding'
    | '/work/email-marketing'
    | '/work/print-digital'
    | '/work/social-media'
    | '/work/video'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ConnectRoute: typeof ConnectRoute
  SkillsRoute: typeof SkillsRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$category': {
      id: '/work/$category'
      path: '/$category'
      fullPath: '/work/$category'
      preLoaderRoute: typeof WorkCategoryRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/blog-content': {
      id: '/work/blog-content'
      path: '/blog-content'
      fullPath: '/work/blog-content'
      preLoaderRoute: typeof WorkBlogContentRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/branding': {
      id: '/work/branding'
      path: '/branding'
      fullPath: '/work/branding'
      preLoaderRoute: typeof WorkBrandingRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/email-marketing': {
      id: '/work/email-marketing'
      path: '/email-marketing'
      fullPath: '/work/email-marketing'
      preLoaderRoute: typeof WorkEmailMarketingRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/print-digital': {
      id: '/work/print-digital'
      path: '/print-digital'
      fullPath: '/work/print-digital'
      preLoaderRoute: typeof WorkPrintDigitalRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/social-media': {
      id: '/work/social-media'
      path: '/social-media'
      fullPath: '/work/social-media'
      preLoaderRoute: typeof WorkSocialMediaRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/video': {
      id: '/work/video'
      path: '/video'
      fullPath: '/work/video'
      preLoaderRoute: typeof WorkVideoRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkCategoryRoute: typeof WorkCategoryRoute
  WorkBlogContentRoute: typeof WorkBlogContentRoute
  WorkBrandingRoute: typeof WorkBrandingRoute
  WorkEmailMarketingRoute: typeof WorkEmailMarketingRoute
  WorkPrintDigitalRoute: typeof WorkPrintDigitalRoute
  WorkSocialMediaRoute: typeof WorkSocialMediaRoute
  WorkVideoRoute: typeof WorkVideoRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkCategoryRoute: WorkCategoryRoute,
  WorkBlogContentRoute: WorkBlogContentRoute,
  WorkBrandingRoute: WorkBrandingRoute,
  WorkEmailMarketingRoute: WorkEmailMarketingRoute,
  WorkPrintDigitalRoute: WorkPrintDigitalRoute,
  WorkSocialMediaRoute: WorkSocialMediaRoute,
  WorkVideoRoute: WorkVideoRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ConnectRoute: ConnectRoute,
  SkillsRoute: SkillsRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
